//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public long OrderID { get; set; }
        public long ProductID { get; set; }
        public int SoldPrice { get; set; }
        public short Quantity { get; set; }
        public Nullable<decimal> ShipmentID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public virtual Package Package { get; set; }
    }
}
