//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Package()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public decimal PackageID { get; set; }
        public Nullable<decimal> InvoiceID { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string TrackingNo { get; set; }
        public bool IsBackOrder { get; set; }
        public long OrderID { get; set; }
        public string StatusCode { get; set; }
        public long UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
    }
}
